# -*- coding: utf-8 -*-
"""Emoji_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o67608qLVsSX9yEHtSibe9SJPcCQ27Z3
"""

from zipfile import ZipFile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
from skimage.feature import hog
import streamlit as st
import os
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC,SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from features import extract_hog_emojis
import joblib

"""program taking image path as input and giving gray scale resized image"""

def process(path):
  img=cv2.imread(path)
  img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  img=cv2.resize(img,(128,128))
  return img



#augmentation

def augment_image(image):
    image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    rows, cols = image.shape[:2]

    angle = np.random.uniform(-15, 15)
    scale = np.random.uniform(0.85, 1.15)
    M_rot = cv2.getRotationMatrix2D(
        (cols / 2, rows / 2),
        angle,
        scale
    )
    image = cv2.warpAffine(image, M_rot, (cols, rows))

    tx = np.random.uniform(-0.10, 0.10) * cols
    ty = np.random.uniform(-0.10, 0.10) * rows
    M_translate = np.float32([
        [1, 0, tx],
        [0, 1, ty]
    ])

    image = cv2.warpAffine(
        image,
        M_translate,
        (cols, rows)
    )
    return image

IMG_SIZE = (228, 228)


def load_and_prepare_data():
    """Load emoji images from zip, augment, and extract features"""
    # Extract zip file if my_emojis directory doesn't exist
    zip_path = "my_emojis.zip"
    if not os.path.exists('my_emojis'):
        with ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall()
    
    images_org=[]
    labels_org=[]
    emoji_dir='my_emojis'
    
    for emotion in os.listdir(emoji_dir):
        if(emotion!="desktop.ini"):
            path=os.path.join(emoji_dir,emotion)
            for image in os.listdir(path):
                img_path=os.path.join(path,image)
                im_read=cv2.imread(img_path)
                if im_read is not None:
                    images_org.append(im_read)
                    labels_org.append(emotion)
    
    images=[]
    labels=[]
    
    for img,lbl in zip(images_org,labels_org):
      img_arr=[img]
      lbl_arr=[lbl]
      for i in range(100):
        new_img=augment_image(img)
        img_arr.append(new_img)
        lbl_arr.append(lbl)
      for image in img_arr:
        images.append(extract_hog_emojis(image))
        labels.append(lbl)
    
    X_train,X_test,y_train,y_test=train_test_split(images,labels,test_size=0.2,random_state=8,stratify=labels)
    return X_train, X_test, y_train, y_test

@st.cache_resource
def get_svc_model():
    X_train, X_test, y_train, y_test = load_and_prepare_data()
    svm_model = SVC(kernel='linear',random_state=42, max_iter=2000)
    svm_model.fit(X_train, y_train)
    return svm_model

@st.cache_resource
def get_rf_model():
    X_train, X_test, y_train, y_test = load_and_prepare_data()
    random_forest_model=RandomForestClassifier(n_estimators=100,random_state=8)
    random_forest_model.fit(X_train,y_train)
    return random_forest_model
