# -*- coding: utf-8 -*-
"""Emoji_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o67608qLVsSX9yEHtSibe9SJPcCQ27Z3
"""

from zipfile import ZipFile
zip_path = "my_emojis.zip"

with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
from skimage.feature import hog
import streamlit as st
import os
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC,SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from features import extract_hog_emojis

"""program taking image path as input and giving gray scale resized image"""

def process(path):
  img=cv2.imread(path)
  img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  img=cv2.resize(img,(128,128))
  return img



#augmentation

def augment_image(image):
    image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    rows, cols = image.shape[:2]

    angle = np.random.uniform(-15, 15)
    scale = np.random.uniform(0.85, 1.15)
    M_rot = cv2.getRotationMatrix2D(
        (cols / 2, rows / 2),
        angle,
        scale
    )
    image = cv2.warpAffine(image, M_rot, (cols, rows))

    tx = np.random.uniform(-0.10, 0.10) * cols
    ty = np.random.uniform(-0.10, 0.10) * rows
    M_translate = np.float32([
        [1, 0, tx],
        [0, 1, ty]
    ])

    image = cv2.warpAffine(
        image,
        M_translate,
        (cols, rows)
    )
    return image

IMG_SIZE = (228, 228)


images_org=[]
labels_org=[]
emoji_dir='my_emojis'

for emotion in os.listdir(emoji_dir):
    if(emotion!="desktop.ini"):
        path=os.path.join(emoji_dir,emotion)
        for image in os.listdir(path):
        img_path=os.path.join(path,image)
        im_read=cv2.imread(img_path)
        images_org.append(im_read)
        labels_org.append(emotion)

images=[]
labels=[]

for img,lbl in zip(images_org,labels_org):
  img_arr=[img]
  lbl_arr=[lbl]
  for i in range(100):
    new_img=augment_image(img)
    img_arr.append(new_img)
    lbl_arr.append(lbl)
  for image in img_arr:
    images.append(extract_hog_emojis(image))
    labels.append(lbl)

X_train,X_test,y_train,y_test=train_test_split(images,labels,test_size=0.2,random_state=8,stratify=labels)

@st.cache_resource
def get_svc_model():
    svm_model = SVC(kernel='linear',random_state=42, max_iter=2000)
    svm_model.fit(X_train, y_train)
    return svm_model
svm_model=get_svc_model()
def show_accuracy(model,Xtest):
  y_pred = model.predict(Xtest)
  print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))

show_accuracy(svm_model,X_test)

@st.cache_resource
def get_rf_model():
    random_forest_model=RandomForestClassifier(n_estimators=100,random_state=8)
    random_forest_model.fit(X_train,y_train)
    return random_forest_model
random_forest_model=get_rf_model()
show_accuracy(random_forest_model,X_test)

import joblib
joblib.dump(random_forest_model,'random_forest_model.pkl')
joblib.dump(svm_model,'svm_model.pkl')
