# -*- coding: utf-8 -*-
"""Shape_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rplS7bFZ_mZqB2cws9a9uD3En4-S2jic

#Mathematical Shape Recognition
"""

#!pip install streamlit

import math
import random
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
import cv2
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import streamlit as st
import joblib

def generate_shape(shape_type, img_size=128):
    img = Image.new("RGB", (img_size, img_size), "white")
    draw = ImageDraw.Draw(img)

    center = img_size // 2
    max_radius = int(img_size * 0.4)

    fill_color = (random.randint(50, 200), random.randint(50, 200), random.randint(50, 200))
    outline_color = "black"

    if shape_type == "Circle":
        draw.ellipse([center - max_radius, center - max_radius, center + max_radius, center + max_radius], fill=fill_color, outline=outline_color, width=2)

    elif shape_type == "Square":
        offset = max_radius
        draw.rectangle([center - offset, center - offset, center + offset, center + offset], fill=fill_color, outline=outline_color, width=2)

    elif shape_type == "Rectangle":
        x=random.randint(0,1)
        comp=random.uniform(0.3,0.99)
        if(x==0):
          w_offset = max_radius
          h_offset = int(max_radius * comp)
        else:
          h_offset = max_radius
          w_offset = int(max_radius * comp)
        draw.rectangle([center - w_offset, center - h_offset, center + w_offset, center + h_offset], fill=fill_color, outline=outline_color, width=2)

    elif shape_type in ["Triangle", "Pentagon", "Hexagon"]:
        sides_map = {"Triangle": 3, "Pentagon": 5, "Hexagon": 6}
        num_sides = sides_map[shape_type]
        points = []
        for i in range(num_sides):
            angle = i * (2 * math.pi / num_sides) - (math.pi / 2) # Subtract 90 degrees to point upward
            x = center + int(max_radius * math.cos(angle))
            y = center + int(max_radius * math.sin(angle))
            points.append((x, y))
        draw.polygon(points, fill=fill_color, outline=outline_color, width=2)

    elif shape_type == "Star":
        points = []
        inner_radius = max_radius // 2
        for i in range(10):
            radius = max_radius if i % 2 == 0 else inner_radius
            angle = i * (2 * math.pi / 10) - (math.pi / 2)
            x = center + int(radius * math.cos(angle))
            y = center + int(radius * math.sin(angle))
            points.append((x, y))
        draw.polygon(points, fill=fill_color, outline=outline_color, width=2)

    elif shape_type == "Ellipse":
        draw.ellipse([center - max_radius, center - int(max_radius * 0.6), center + max_radius, center + int(max_radius * 0.6)], fill=fill_color, outline=outline_color, width=2)

    return img

test_image = generate_shape("Pentagon", img_size=128)
test_image.show()
plt.imshow(test_image)

def extract_shape_metrics(img):
    img=np.array(img)
    img=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    _, thresh = cv2.threshold(img, 240, 255, cv2.THRESH_BINARY_INV)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contour = max(contours, key=cv2.contourArea)
    perimeter = cv2.arcLength(contour, True)
    epsilon = 0.02 * perimeter
    approx = cv2.approxPolyDP(contour, epsilon, True)
    corner_count = len(approx)

    x, y, w, h = cv2.boundingRect(contour)
    aspect_ratio = float(w) / h

    area = cv2.contourArea(contour)
    bounding_box_area = w * h
    extent = float(area) / bounding_box_area

    hull = cv2.convexHull(contour)
    hull_area = cv2.contourArea(hull)
    solidity = float(area) / hull_area if hull_area > 0 else 0

    moments = cv2.moments(contour)
    hu_moments = cv2.HuMoments(moments).flatten()

    hu_log = -np.sign(hu_moments) * np.log10(np.abs(hu_moments) + 1e-10)

    feature_vector = [corner_count, aspect_ratio, extent, solidity] + list(hu_log)
    return feature_vector
joblib.dump(extract_shape_metrics,'extract_shape_metrics.pkl')

#augmentation
def augment_image(image):
    rows, cols = image.shape[:2]

    angle = np.random.uniform(-15, 15)
    scale = np.random.uniform(0.85, 1.15)
    M_rot = cv2.getRotationMatrix2D(
        (cols / 2, rows / 2),
        angle,
        scale
    )
    image = cv2.warpAffine(image, M_rot, (cols, rows))

    tx = np.random.uniform(-0.10, 0.10) * cols
    ty = np.random.uniform(-0.10, 0.10) * rows
    M_translate = np.float32([
        [1, 0, tx],
        [0, 1, ty]
    ])

    image = cv2.warpAffine(
        image,
        M_translate,
        (cols, rows)
    )
    return image

@st.cache_resource
def get_features_labels():
  features=[]
  labels=[]
  my_shapes=['Circle','Square','Rectangle','Triangle','Pentagon','Hexagon','Star','Ellipse']
  for shape in my_shapes:
    for i in range(15):
      shp=generate_shape(shape)
      features.append(extract_shape_metrics(shp))
      labels.append(shape)
      for i in range(15):
        # Convert PIL Image to NumPy array before augmentation
        new_shp=extract_shape_metrics(augment_image(np.array(shp)))
        features.append(new_shp)
        labels.append(shape)
  features=pd.DataFrame(features,columns=['corners','aspect_ratio','extent','solidity','hu1','hu2','hu3','hu4','hu5','hu6','hu7'])
  return features,labels
features,labels=get_features_labels()

X_train,X_test,y_train,y_test=train_test_split(features,labels,test_size=0.2,random_state=6)

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

@st.cache_resource
def get_tree_model():
  tree_model=DecisionTreeClassifier(min_samples_split=4,random_state=0)
  tree_model.fit(X_train,y_train)
tree_model=get_tree_model()

@st.cache_resource
def get_knn_model():
  knn_model=KNeighborsClassifier(n_neighbors=5)
  knn_model.fit(X_train,y_train)
knn_model=get_knn_model()

joblib.dump(tree_model,'decision_tree_model.pkl')
joblib.dump(knn_model,'knn_model.pkl')

def show_accuracy(model):
  y_pred=model.predict(X_test)
  print(f'Accuracy:\t{accuracy_score(y_test,y_pred)}')
  print(f'classification_report:\n{classification_report(y_test,y_pred)}')

show_accuracy(tree_model)
show_accuracy(knn_model)
